### ISSUE TITLE
Demo site returns 'Application Error'

### ISSUE THREAD

**Issue by ryaaahs** [Flowko/gitprofile#8]
When loading the demo site 'https://gitpro.herokuapp.com/' 

It returns an Application error.
![image](https://user-images.githubusercontent.com/46785810/163908972-58ed7811-8305-4015-909d-44aba8f712fd.png)

Looking into the header of the failed GET request, shows it was a 503 status.
![image](https://user-images.githubusercontent.com/46785810/163909192-23abee3c-6800-46de-afa4-5e14323b054b.png)

**Comment by Flowko** [comment]
thanks for checking it out, sadly i ran out of free dyno hours, but u can always try to clone the repo and check it locally. (u need to create a github api and insert it into ur .env file under the same name) 
i'll probably end up redoing alot of stuff and paying for a good hosting service later on.
